package wasm-serde:bench;

world component {
    record small-input {
       a: string,
       b: u32,
       c: tuple<u32, u32, u32>,
    }

    record big-input-element-payload {
       nonce: string,
       message: string,
       recipient: string,
    }

    record big-input-element {
       payload: big-input-element-payload,
       standard: string,
       signature: string,
       public-key: string,
    }

    record big-input {
       signed: list<big-input-element>,
    }

    import input: func() -> list<u8>;

    export noop: func();

    export run-small: func();
    export run-big: func();

    export run-small-bytes: func(input: list<u8>);
    export run-big-bytes: func(input: list<u8>);

    export run-small-typed: func(input: small-input);
    export run-big-typed: func(input: big-input);
}
