package myapp:app@0.1.0;

interface custom {
    record test-record {
        foo: string,
        bar: string,
    }

    greet: func(s: string) -> string;
    add: func(a: u64, b: u64) -> u64;
    foo: func(t: test-record) -> u64;
}

world app {
    export custom;
}
