package cosmonic:serde@0.1.0;

interface deserializer {
    use cosmonic:reflect/reflect@0.1.0.{record-type, variant-type, list-type, tuple-type, flags-type, enum-type, option-type, result-type, %type, value};

    resource error {
        to-string: func() -> string;
    }

    from-list: func(buf: list<u8>, %type: %type) -> result<value, error>;
}

interface serializer {
    use cosmonic:reflect/reflect@0.1.0.{value};

    from-value: func(value: value) -> list<u8>;
}

world imports {
    import cosmonic:reflect/reflect@0.1.0;

    import deserializer;
    import serializer;
}

world format {
    export cosmonic:reflect/reflect@0.1.0;

    export deserializer;
    export serializer;
}
